---
- hosts: all
  become: yes

  roles:
  - role: ../roles/gather-desktop-environment-facts
  - role: ../roles/ubuntu-pre
  - role: ../roles/crownlabs
    when: crownlabs_mode
  - role: ../roles/firefox
    when: install_desktop_environment is defined and install_desktop_environment == "true"
  - role: ../roles/ubuntu-post
