apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-crownlabs-images
  namespace: docker-registry
  labels:
    app.kubernetes.io/name: list-crownlabs-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: list-crownlabs-images
  template:
    metadata:
      labels:
        app.kubernetes.io/name: list-crownlabs-images
    spec:
      automountServiceAccountToken: false
      containers:
      - name: list-crownlabs-images
        image: crownlabs/list-crownlabs-images:v0.1-crown
        imagePullPolicy: Always
        args:
        - --webserver-port
        - "8080"
        - --cache-duration-minutes
        - "15"
        - --registry-url
        - http://docker-registry.docker-registry:5000
        - --advertised-registry-name
        - registry.internal.crown-labs.ipv6.polito.it
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
        resources:
          requests:
            cpu: "100m"
            memory: 100Mi
          limits:
            cpu: "200m"
            memory: 250Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 100000
          runAsGroup: 100000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: list-crownlabs-images
  namespace: docker-registry
spec:
  selector:
    app.kubernetes.io/name: list-crownlabs-images
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: list-crownlabs-images
  name: list-crownlabs-images
  namespace: docker-registry
spec:
  rules:
  - host: registry.crown-labs.ipv6.polito.it
    http:
      paths:
      - backend:
          serviceName: list-crownlabs-images
          servicePort: http
        path: /list-crownlabs-images
        pathType: Exact
  tls:
  - hosts:
    - registry.crown-labs.ipv6.polito.it
    secretName: certificate-registry