---
- name: Install the ifenslave dependency (required to create bonds)
  apt:
    name: ifenslave
    state: present
  when: host_role != "master"

- name: Ensure presence of the “bonding” module
  modprobe:
    name: 8021q
    state: present
  when: host_role != "master"

- name: Load bonding modules during boot
  lineinfile:
    path: /etc/modules
    state: present
    line: bonding
  when: host_role != "master"

- name: Allow the connection from/to the master VM (1)
  iptables:
    chain: FORWARD
    source: "{{ master_ip_address }}"
    jump: ACCEPT
  when: host_role == "master-host"

- name: Allow the connection from/to the master VM (2)
  iptables:
    chain: FORWARD
    destination: "{{ master_ip_address }}"
    jump: ACCEPT
  when: host_role == "master-host"

- name: Update /etc/netplan/50-cloud-init.yaml
  template:
    src: templates/50-cloud-init-{{ host_role }}.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Apply netplan configuration

# For some reasons, LADISPE seems to have IPv6 running in its network,
# although there's no IPv6 connectivity that goes beyond the lab.
# This means that when we try to connect to an IPv4/6-host (e.g., google),
# the connection is started in IPv6, leading to a long waiting time before
# recognizing that the path to host does not exist. So, much better to
# disable the IPv6 stack.
- name: Disable IPv6 Networking (1)
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable IPv6 Networking (2)
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

# Apparently, due to a bug, the above configurations are not sufficient
# to persist the modification across reboots, and it is necessary to
# pass the "ipv6.disable=1" parameter during the boot time.
- name: Disable IPv6 Networking (3)
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=(?!.*ipv6\.disable)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable=1\2'
  notify: Run update-grub
