# permissions to do viewer labtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labtemplate-viewer-role
rules:
- apiGroups:
  - template.crown.team.com
  resources:
  - labtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.crown.team.com
  resources:
  - labtemplates/status
  verbs:
  - get
