apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exam-agent.fullname" . }}
  labels:
    {{- include "exam-agent.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exam-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "exam-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exam-agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "exam-agent.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--namespace={{ .Values.configurations.targetNamespace }}"
            - "--allowed-ips={{ .Values.configurations.allowedIPs }}"
            - "--base-path={{ .Values.exposition.basePath }}"
          ports:
            - name: api
              containerPort: 8888
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: api
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "exam-agent.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
