apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbacResourcesName }}-view-templates
  namespace: {{ .Values.configurations.targetNamespace }}
  labels:
    {{- include "exam-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crownlabs-view-templates
subjects:
  - kind: ServiceAccount
    name: {{ include "exam-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbacResourcesName }}-manage-instances
  namespace: {{ .Values.configurations.targetNamespace }}
  labels:
    {{- include "exam-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crownlabs-manage-instances
subjects:
  - kind: ServiceAccount
    name: {{ include "exam-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
