apiVersion: v1
kind: Service
metadata:
  name: {{ include "exam-agent.fullname" . }}
spec:
  selector:
    {{- include "exam-agent.selectorLabels" . | nindent 6 }}
  ports:
  - name: api
    port: 80
    targetPort: api
