#!/bin/sh

#from the original Xvnc-session, just vncconfig has been removed

test x"$SHELL" = x"" && SHELL=/bin/bash
test x"$1"     = x"" && set -- default

"$SHELL" -l <<EOF
exec /etc/X11/Xsession "$@"
EOF
vncserver -kill "$DISPLAY"
