#!/bin/sh

#from the original Xvnc-session:
# > remove vncconfig
# > add xhost (to enable connections to the X server from external containers)
# > start window manager (fluxbox)

test x"$SHELL" = x"" && SHELL=/bin/bash
test x"$1"     = x"" && set -- default

"$SHELL" -l <<EOF
xhost +
fluxbox
EOF
vncserver -kill "$DISPLAY"
