#!/bin/sh

#from the original Xvnc-session:
# > remove vncconfig
# > add xhost (to enable connections to the X server from external containers)
# > start window manager (fluxbox)

test "$SHELL" = "" && SHELL=/bin/bash
test "$1"     = "" && set -- default

"$SHELL" -l <<EOF
xhost +
fluxbox
EOF
vncserver -kill "$DISPLAY"
