apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: {{ namespace_name }}
spec:
  hard:
    limits.cpu: "20"
    limits.memory: 30Gi
    requests.cpu: "20"
    requests.memory: 30Gi
    count/labinstances.instance.crown.team.com: "1"