apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: test-mattia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: mlvc/crown
          imagePullPolicy: Always
          name: frontend
          args: [-e, OIDC_CLIENT_ID="k8s",
                -e, OIDC_PROVIDER_URL="https://auth.crown-labs.ipv6.polito.it:4443/auth/realms/virtlabs",
                -e, APISERVER_URL="https://apiserver.crown-labs.ipv6.polito.it",
                -e, OIDC_REDIRECT_URI="http://localhost:8000"
          ]
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred

