apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: frontend-auxiliary
  namespace: frontend
spec:
  rules:
    - host: crownlabs.polito.it
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /callback
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /logout
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /userview
  tls:
    - hosts:
        - crownlabs.polito.it
      secretName: frontend-cert
