# Default values for instmetrics
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: crownlabs/instmetrics
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

configurations:
  runtimeEndpoint: unix:///run/dockershim.sock
  containerRuntime: /run/dockershim.sock
  dockerSocket: /var/run/docker.sock
  connectionTimeout:  10s
  updatePeriod: 4s
  grpcPort: 9090

automountServiceAccountToken: false

nameOverride: ""
fullnameOverride: ""

daemonsetAnnotations: {}
podAnnotations: {}

podSecurityContext: 
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false

service:
  type: ClusterIP
  port: 9090


resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 150Mi

tolerations: []
  # these tolerations are to have the daemonset runnable on control plane nodes
  # uncomment them to enable the daemonset pods to be also scheduled on control plane nodes
  # - key: node-role.kubernetes.io/control-plane
  #   operator: Exists
  #   effect: NoSchedule
  # - key: node-role.kubernetes.io/master
  #   operator: Exists
  #   effect: NoSchedule

