// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/auth_iface.go
//
// Generated by this command:
//
//	mockgen -source=../../utils/auth_iface.go
//

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	context "context"
	reflect "reflect"

	gocloak "github.com/Nerzal/gocloak/v13"
	gomock "go.uber.org/mock/gomock"
)

// MockKeycloakActorIface is a mock of KeycloakActorIface interface.
type MockKeycloakActorIface struct {
	ctrl     *gomock.Controller
	recorder *MockKeycloakActorIfaceMockRecorder
	isgomock struct{}
}

// MockKeycloakActorIfaceMockRecorder is the mock recorder for MockKeycloakActorIface.
type MockKeycloakActorIfaceMockRecorder struct {
	mock *MockKeycloakActorIface
}

// NewMockKeycloakActorIface creates a new mock instance.
func NewMockKeycloakActorIface(ctrl *gomock.Controller) *MockKeycloakActorIface {
	mock := &MockKeycloakActorIface{ctrl: ctrl}
	mock.recorder = &MockKeycloakActorIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeycloakActorIface) EXPECT() *MockKeycloakActorIfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockKeycloakActorIface) CreateUser(ctx context.Context, username, email, firstName, lastName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, email, firstName, lastName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockKeycloakActorIfaceMockRecorder) CreateUser(ctx, username, email, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockKeycloakActorIface)(nil).CreateUser), ctx, username, email, firstName, lastName)
}

// DeleteUser mocks base method.
func (m *MockKeycloakActorIface) DeleteUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockKeycloakActorIfaceMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockKeycloakActorIface)(nil).DeleteUser), ctx, userID)
}

// GetAccessToken mocks base method.
func (m *MockKeycloakActorIface) GetAccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockKeycloakActorIfaceMockRecorder) GetAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockKeycloakActorIface)(nil).GetAccessToken))
}

// GetUser mocks base method.
func (m *MockKeycloakActorIface) GetUser(ctx context.Context, username string) (*gocloak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username)
	ret0, _ := ret[0].(*gocloak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockKeycloakActorIfaceMockRecorder) GetUser(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockKeycloakActorIface)(nil).GetUser), ctx, username)
}

// IsInitialized mocks base method.
func (m *MockKeycloakActorIface) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockKeycloakActorIfaceMockRecorder) IsInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockKeycloakActorIface)(nil).IsInitialized))
}

// Reset mocks base method.
func (m *MockKeycloakActorIface) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockKeycloakActorIfaceMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockKeycloakActorIface)(nil).Reset))
}
