version: 2
updates:
  - package-ecosystem: npm
    directory: /qlkube
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      qlkube:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      frontend:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /operators
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      operators:
        applies-to: security-updates
        patterns: ["*"]
