sig/api:
  - operators/**/*

sig/ui:
  - dashboard/**/*
  - frontend/**/*

sig/operations:
  - infrastructure/**/*

sig/user-environment:
  - provisioning/virtual-machines/**/*
  - provisioning/containers/**/*

sig/devops:
  - .github/**/*
  - ./**/deploy/**/*

sig/community:
  - AUTHORS
  - ./**/*/README.md
  - LICENSE
  - README.md
  - documentation/**/*
