apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress
  namespace: ingress-nginx
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
    - ingress-nginx
  selector:
    matchLabels:
      app: nginx-metrics-svc
