apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-certificate
  namespace: default
spec:
  # The secret where the generated certificate is stored
  secretName: example-certificate-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: example.crown-labs.ipv6.polito.it
  dnsNames:
  - example.crown-labs.ipv6.polito.it
  uriSANs:
  - example.crown-labs.ipv6.polito.it
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
