version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    goheader:
      values:
        const:
          AUTHORS: Politecnico di Torino
      template: |-
        Copyright 2020-{{ YEAR }} {{ AUTHORS }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - govet
        text: declaration of "(err|ctx)" shadows declaration at
      - linters:
          - revive
        text: don't use an underscore in package name
      - linters:
          - revive
        text: should not use dot imports
      - linters:
          - staticcheck
        text: 'ST1003: should not use underscores in package names'
      - linters:
          - gosec
          - dupl
        path: _test\.go
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    paths:
      - zz_generated.*.go
      - .*mock.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netgroup-polito/CrownLabs)
    goimports:
      local-prefixes:
        - github.com/netgroup-polito/CrownLabs
  exclusions:
    generated: lax
    paths:
      - zz_generated.*.go
      - .*mock.go
      - third_party$
      - builtin$
      - examples$
