ignorePatterns:
  - pattern: "^https://.*\\.example\\.com/.*$"
  # This link often returns http code 429 ("too many requests") when executed from github  
  - pattern: "^https://developer.hashicorp.com/packer$"
dirs:
  - .
