  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: calico-node
    namespace: kube-system
  spec:
    template:
      spec:
        containers:
        - name: calico-node
          env:
          - name: CALICO_IPV4POOL_CIDR
            value: "172.16.0.0/16"
