apiVersion: v1
kind: Namespace
metadata:
  name: tenant-john-doe
  labels:
    crownlabs.polito.it/operator-selector: local
---
apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: green-tea-6831
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: green-tea
    namespace: workspace-tea
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe
---
apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: instance-vscode-python-proxyenabled
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: vscode-python-proxyenabled
    namespace: workspace-standalone
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe
---
apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: instance-jupyterlab
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: jupyterlab
    namespace: workspace-standalone
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe
---
apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: instance-vscode-c-cpp-persistent
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: vscode-c-cpp-persistent
    namespace: workspace-standalone
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe