# Default values for exams agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configurations:
  # Comma separated list of whitelisted IPs (can include glob expressions) that can create instances
  allowedIPs: ""
  targetNamespace: "crownlabs-exam"

exposition:
  host: exams.crownlabs.polito.it
  basePath: "/api"

image:
  repository: crownlabs/exam-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
podAnnotations: {}
ingressAnnotations:
  nginx.ingress.kubernetes.io/custom-http-errors: "418"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 20000
  runAsGroup: 20000
  privileged: false

resources:
  limits:
    memory: 500Mi
    cpu: 1000m
  requests:
    memory: 100Mi
    cpu: 100m

rbacResourcesName: crownlabs-exam-agent
