apiVersion: batch/v1
kind: Job
metadata:
  name: crownlabs-img-creator
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: packer-image-creator
        image: crownlabs/vms-provisioner:latest
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "16Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "6000m"
        env:
        - name: ISO_URL
          value: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        - name: ISO_CHECKSUM
          value: sha256:b8e4d5bd9b576c3fc5c5ad48bb6e0b92fbdeeb53c4af88a898ef4aba949e75d0
        - name: INSTALL_DESKTOP_ENVIRONMENT
          value: "true"
        - name: ANSIBLE_PLAYBOOK
          value: ubuntu-base.yml
        - name: DISK_SIZE
          value: 10G
        - name: MEMORY
          value: '2048'

        - name: GIT_ANSIBLE_URL
          value: https://github.com/netgroup-polito/CrownLabs.git
        - name: GIT_ANSIBLE_BRANCH
          value: master

        - name: IMAGE_NAME
          value: ubuntu22-base
        - name: IMAGE_TAG
          value: '2023-03-31-0'

        - name: TARGET_REGISTRY
          value: harbor.crownlabs.polito.it
        - name: REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: crownlabs-img-creator-registry
              key: username
        - name: REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: crownlabs-img-creator-registry
              key: password
        - name: REGISTRY_PREFIX
          value: crownlabs-containerdisks
