{{- $webssh := default dict .Values.webssh }}
{{- $ingress := default dict $webssh.ingress }}
{{- if and $webssh.expositionEnabled (not .Values.global.gateway.gatewayApiMode) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bastion.fullname" . }}-webssh
  labels:
    {{- include "webssh.labels" . | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $ingress.hostname }}
      http:
        paths:
          - path: {{ $ingress.path }}
            pathType: {{ $ingress.pathType }}
            backend:
              service:
                name: {{ include "bastion.fullname" . }}-webssh
                port:
                  name: webssh
  {{- if $ingress.secret }}
  tls:
    - hosts:
        - {{ $ingress.hostname }}
      secretName: {{ $ingress.secret }}
  {{- end }}
{{- end }}
