---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
kind: RoleBinding
metadata:
  name: create-labs
  namespace: test-guest # This only grants permissions within the "development" namespace.
subjects:
- kind: User
  name: guest # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: labinstance-consumer-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
kind: RoleBinding
metadata:
  name: get-labs
  namespace: test-guest # This only grants permissions within the "development" namespace.
subjects:
- kind: Group
  name: kubernetes:cloud-computing # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: labtemplate-consumer-operator
  apiGroup: rbac.authorization.k8s.io
