# Default values for kubedb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # License for the product.
  # Get a license by following the steps from [here](https://kubedb.com/docs/latest/setup/install/enterprise#get-a-trial-license).
  # Example:
  # helm install appscode/kubedb \
  #   --set-file global.license=/path/to/license/file
  # or
  # helm install appscode/kubedb \
  #   --set global.license=<license file content>
  license: ""

  # Docker registry used to pull KubeDB related images
  registry: ""

  # Docker registry fqdn used to pull KubeDB related images.
  # Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
  registryFQDN: ""

  # Specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  #
  # Example:
  # helm template charts/kubedb \
  #   --set global.imagePullSecrets[0].name=sec0 \
  #   --set global.imagePullSecrets[1].name=sec1
  imagePullSecrets: []

  # Skip generating cleaner job YAML
  skipCleaner: false

kubedb-catalog:
  # If enabled, installs the kubedb-catalog chart
  enabled: true
kubedb-community:
  # If enabled, installs the kubedb-community chart
  enabled: true
  enableAnalytics: false
kubedb-enterprise:
  # If enabled, installs the kubedb-enterprise chart
  enabled: false
kubedb-autoscaler:
  # If enabled, installs the kubedb-autoscaler chart
  enabled: false

