# permissions to do viewer labinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labinstance-viewer-role
rules:
- apiGroups:
  - instance.crown.team.com
  resources:
  - labinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - instance.crown.team.com
  resources:
  - labinstances/status
  verbs:
  - get
