{{- if .Values.global.gateway.securityPolicy.enabled | default true }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "crownlabs.fullname" . }}-instauth-callback
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.global.gateway.name }}
      sectionName: https
  rules:
    - matches:
        - path:
            type: Exact
            value: {{ .Values.global.gateway.securityPolicy.callback.path }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "crownlabs.fullname" . }}-secpol-dummy-backend
          port: 80
{{- end }}
