---
# vars file for crownlabs

unnecessary_packages:
- alsa-base
- alsa-utils
- laptop-detect
- libasound2-plugins
- network-manager-gnomes
- rfkill
- usbutils
- wireless-tools
- wpasupplicant
- xfce4-screensaver

unnecessary_services:
- apport.service
- man-db.timer
- man-db.service
