apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "image-list.labels" . | nindent 4 }}
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - imagelists
  verbs:
  - get
  - create
  - update
