apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-list.labels" . | nindent 4 }}
data:
  registries: |
    {{- .Values.registries | toYaml | nindent 4 }}
