apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "image-list.fullname" . }}
  labels:
    {{- include "image-list.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "image-list.fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ include "image-list.version" . }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - --configmap-name={{ .Values.configMap.name }}
                - --configmap-namespace={{ .Values.configMap.namespace }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
