apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-list.fullname" . }}
  labels:
    {{- include "image-list.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-list.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "image-list.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "image-list.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "image-list.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --advertised-registry-name={{ .Values.configurations.advRegistryName }}
            - --image-list-name={{ .Values.configurations.imageListName }}
            - --registry-url={{ .Values.configurations.registryUrl }}
            - --update-interval={{ .Values.configurations.updateInterval }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "image-list.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
