apiVersion: v1
kind: Service
metadata:
  name: {{ include "bastion-operator.fullname" . }}-metrics
  labels:
    {{- include "bastion-operator.labels" . | nindent 4 }}
    {{- include "bastion-operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bastion-operator.selectorLabels" . | nindent 4 }}
