apiVersion: v1
kind: Service
metadata:
  name: {{ include "bastion-operator.fullname" . }}
  labels:
    {{- include "bastion-operator.labels" . | nindent 4 }}
{{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh-alt
      protocol: TCP
      name: ssh-alt
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    {{- include "bastion-operator.selectorLabels" . | nindent 4 }}

---

{{- if .Values.webssh.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bastion-operator.fullname" . }}-webssh
  labels:
    {{- include "webssh.labels" . | nindent 4 }}
    {{- include "bastion-operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  type: {{ .Values.webssh.service.type }}
  ports:
    - port: {{ .Values.webssh.service.port }}
      targetPort: {{ .Values.webssh.service.targetPort }}
      protocol: TCP
      name: webssh
  selector:
    {{- include "webssh.selectorLabels" . | nindent 4 }}
{{- end }}
