apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["crownlabs.polito.it"]
  resources: ["instances", "instances/status"]
  verbs: ["get","list","watch","create","update","patch","delete","deleteCollection"]

- apiGroups: ["crownlabs.polito.it"]
  resources: ["instancesnapshots", "instancesnapshots/status"]
  verbs: ["get","list","watch","create","update","patch"]

- apiGroups: ["crownlabs.polito.it"]
  resources: ["templates", "tenants"]
  verbs: ["get","list","watch"]

- apiGroups: ["crownlabs.polito.it"]
  resources: ["sharedvolumes", "sharedvolumes/status"]
  verbs: ["get","list","watch","create","update","patch","delete","deleteCollection"]

- apiGroups: [""]
  resources: ["namespaces","persistentvolumes","pods"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["secrets","events","persistentvolumeclaims"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch","create","patch","update", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","list","watch","create","patch","update","delete"]

- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["get","list","watch","create", "patch", "update"]

- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create", "patch", "update"]
