apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbacResourcesName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "instance-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
