{{- if and (.Values.configurations.generic.gatewayApiMode | default .Values.global.gateway.gatewayApiMode | default false) (.Values.securityPolicyTemplate.enabled | default false) }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "instance-operator.fullname" . }}-auth-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
spec:
  targetRefs: []
  {{- if .Values.securityPolicyTemplate.extAuth }}
  extAuth:
    failOpen: {{ .Values.securityPolicyTemplate.extAuth.failOpen | default false }}
    headersToExtAuth:
      - Cookie
      - Authorization
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.securityPolicyTemplate.extAuth.http.backendRef.name | default "oauth2-proxy" | quote }}
          namespace: {{ .Values.securityPolicyTemplate.extAuth.http.backendRef.namespace | default .Release.Namespace | quote }}
          port: {{ .Values.securityPolicyTemplate.extAuth.http.backendRef.port | default 4180 }}
  {{- else if .Values.securityPolicyTemplate.oidc }}
  oidc:
    provider:
      issuer: {{ .Values.securityPolicyTemplate.oidc.provider.issuer | quote }}
    clientID: {{ .Values.securityPolicyTemplate.oidc.clientID | quote }}
    clientSecret:
      name: {{ .Values.securityPolicyTemplate.oidc.clientSecret.name | quote }}
      namespace: {{ .Values.securityPolicyTemplate.oidc.clientSecret.namespace | default .Release.Namespace | quote }}
    {{- if .Values.securityPolicyTemplate.oidc.redirectURL }}
    redirectURL: {{ .Values.securityPolicyTemplate.oidc.redirectURL | quote }}
    {{- end }}
  {{- end }}
{{- end }}
