{{- if and (.Values.configurations.generic.gatewayApiMode | default .Values.global.gateway.gatewayApiMode | default false) (.Values.securityPolicyTemplate.enabled | default false) }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "instance-operator.fullname" . }}-auth-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
spec:
  targetRefs: []
  {{- toYaml .Values.securityPolicyTemplate.spec | nindent 2 }}
{{- end }}
