apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "instance-operator.fullname" . }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
    {{- include "instance-operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "instance-operator.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: op-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "instance-operator.fullname" . }}-automation
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
    {{- include "instance-operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "instance-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: automation
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: auto-metrics
      path: /metrics
      interval: 15s
