apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-metrics
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    {{- include "operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
