apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.configurations.keycloak.clientId }}
  clientSecret: {{ .Values.configurations.keycloak.clientSecret }}
