apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nextcloud-db-cluster
  namespace: nextcloud
spec:
  teamId: "nextcloud"
  volume:
    storageClass: "rook-ceph-block"
    size: 10Gi
  numberOfInstances: 3
  users:
    nextcloud:  # database owner
    - superuser
    - createdb
  databases:
   nextcloud: nextcloud  # dbname: owner
  postgresql:
    version: "12"
