apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbacResourcesName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}

---

# The tenant operator needs to be granted the CrownLabs sandbox permissions,
# in order to be able of creating the corresponding rolebindings for the tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbacResourcesName }}-sandbox
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.configurations.sandboxClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
