apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-operator.fullname" . }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  keycloak-user: {{ .Values.configurations.keycloak.user }}
  keycloak-pass: {{ .Values.configurations.keycloak.pass }}
