apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-operator.webhookname" . }}
spec:
  selector:
    {{- include "tenant-operator.selectorLabels" . | nindent 6 }}
  ports:
  - name: https
    port: 443
    targetPort: webhook
