{{ if .Values.webhook.enableMutating }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tenant-operator.webhookname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "tenant-operator.webhookname" . }}
webhooks:
- name: mutate.tenant.crownlabs.polito.it
  failurePolicy: Fail
  admissionReviewVersions:
  - v1
  rules:
  - apiGroups:   ["crownlabs.polito.it"]
    apiVersions: ["v1alpha2"]
    operations:  ["CREATE","UPDATE"]
    resources:   ["tenants"]
    scope:       "Cluster"
  clientConfig:
    service:
      name: {{ include "tenant-operator.webhookname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha2-tenant
      port: 443
  sideEffects: None
{{ end }}
