apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configs.name }}
  labels:
    {{- include "crownmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: crownmail
stringData:
  smtp-config.yaml: |-
    smtpServer: {{ .Values.configs.smtp.server }}
    smtpPort: {{ .Values.configs.smtp.port | quote }}
    smtpIdentity: {{ .Values.configs.smtp.identity }}
    smtpUsername: {{ .Values.configs.smtp.username }}
    smtpPassword: {{ .Values.configs.smtp.password }}
    smtpFrom: {{ .Values.configs.smtp.from }}
