apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configs.name }}
  labels:
    {{- include "crownmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: crownmail
stringData:
{{- range $path, $_ := .Files.Glob (printf "%s/**" $.Values.configs.sourceFolder) }}
  {{- $key := $path | replace (printf "%s/" $.Values.configs.sourceFolder) "" | replace "/" "." }}
  {{ $key }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- /* Config overrides from Helm values - last entry wins, so values override files */ -}}
{{- if .Values.configs.overrides }}
{{- range $configKey, $configValue := .Values.configs.overrides }}
  {{ $configKey }}-config.yaml: |-
{{ $configValue | toYaml | indent 4 }}
{{- end }}
{{- end }}
