# Default values for image-list.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configurations:
  registryUrl: http://docker-registry.docker-registry:5000
  advRegistryName: registry.crownlabs.example.com
  imageListName: crownlabs-virtual-machine-images
  updateInterval: 60

image:
  repository: crownlabs/crownlabs-image-list
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  runAsUser: 100000
  runAsGroup: 100000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 200Mi

rbacResourcesName: crownlabs-image-list
