apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudimg-registry.fullname" . }}
  labels:
    {{ include "cloudimg-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "cloudimg-registry.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
