apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-bind-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 130.192.225.79
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-bind-exporter
  namespace: monitoring
  labels:
    app: prometheus-bind-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-bind-exporter
  namespace: monitoring
  labels:
    app: prometheus-bind-exporter
spec:
  endpoints:
  - honorLabels: true
    interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: prometheus-bind-exporter
