apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-internal-service-monitor
  namespace: ingress-nginx-internal
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
    - ingress-nginx-internal
  selector:
    matchLabels:
      app: nginx-metrics-svc
