// Copyright 2020-2026 Politecnico di Torino
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InstanceSnapshotSpec defines the desired state of InstanceSnapshot.
type InstanceSnapshotSpec struct {
	// Instance is the reference to the persistent VM instance to be snapshotted.
	Instance GenericRef `json:"instanceRef"`

	// Environment represents the name of the environment to be snapshotted.
	// +kubebuilder:validation:Pattern="^[a-z\\d][a-z\\d-]{2,10}[a-z\\d]$"
	Environment string `json:"environmentRef"`

	// ImageName is an optional user-defined name for the snapshot image.
	// +optional
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
	ImageName string `json:"imageName,omitempty"`

	// Description is an optional human-readable description of the snapshot.
	// +optional
	// +kubebuilder:validation:MaxLength=512
	Description string `json:"description,omitempty"`

	// Tenant is the reference to the Tenant who created the snapshot.
	// If not specified, it is automatically populated from the source Instance.
	// +optional
	Tenant GenericRef `json:"tenantRef,omitempty"`
}

// SnapshotPhase describes the current phase of the InstanceSnapshot.
// +kubebuilder:validation:Enum="";Pending;Processing;Completed;Failed
type SnapshotPhase string

const (
	// SnapshotPhasePending means the snapshot is being created.
	SnapshotPhasePending SnapshotPhase = "Pending"
	// SnapshotPhaseProcessing means the snapshot is being processed.
	SnapshotPhaseProcessing SnapshotPhase = "Processing"
	// SnapshotPhaseCompleted means the snapshot has been successfully created.
	SnapshotPhaseCompleted SnapshotPhase = "Completed"
	// SnapshotPhaseFailed means the snapshot creation failed.
	SnapshotPhaseFailed SnapshotPhase = "Failed"
)

// SnapshotArtifact describes the final artifact generated by the snapshot.
type SnapshotArtifact struct {
	// DataVolumeRef points to the generated DataVolume.
	DataVolumeRef GenericRef `json:"dataVolumeRef"`

	// VolumeSize reports the dimension of the generated datavolume.
	VolumeSize resource.Quantity `json:"volumeSize"`
}

// InstanceSnapshotStatus defines the observed state of InstanceSnapshot.
type InstanceSnapshotStatus struct {
	// Phase is the current phase of the snapshot.
	Phase SnapshotPhase `json:"phase"`
	// Artifact contains references to the generated resources.
	// +optional
	Artifact SnapshotArtifact `json:"artifact,omitempty"`
	// Conditions hold the latest available observations of the snapshot state.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName="isnap"
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Tenant",type=string,JSONPath=`.spec.tenantRef.name`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// InstanceSnapshot is the Schema for the instancesnapshots API.
type InstanceSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   InstanceSnapshotSpec   `json:"spec,omitempty"`
	Status InstanceSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceSnapshotList contains a list of InstanceSnapshot.
type InstanceSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceSnapshot `json:"items"`
}

func init() {
	SchemeBuilder.Register(&InstanceSnapshot{}, &InstanceSnapshotList{})
}
