// Copyright 2020-2026 Politecnico di Torino
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha2

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SnapshotDestinationScope defines the scope where the snapshot will be saved.
// +kubebuilder:validation:Enum=Private;Workspace;Public
type SnapshotDestinationScope string

const (
	// PrivateScope indicates the snapshot is saved in the user's private namespace.
	PrivateScope SnapshotDestinationScope = "Private"
	// WorkspaceScope indicates the snapshot is saved in the workspace namespace.
	WorkspaceScope SnapshotDestinationScope = "Workspace"
	// PublicScope indicates the snapshot is saved in a public catalog namespace.
	PublicScope SnapshotDestinationScope = "Public"
)

// InstanceSnapshotDisk describes the properties of the disk being snapshotted.
type InstanceSnapshotDisk struct {
	// StorageClassName is the storage class of the underlying PVC.
	StorageClassName *string `json:"storageClassName,omitempty"`
	// VolumeMode is the volume mode of the underlying PVC.
	VolumeMode *corev1.PersistentVolumeMode `json:"volumeMode,omitempty"`
	// AccessModes are the access modes of the underlying PVC.
	AccessModes []corev1.PersistentVolumeAccessMode `json:"accessModes,omitempty"`
	// Size is the size of the underlying PVC.
	Size resource.Quantity `json:"size,omitempty"`
}

// InstanceSnapshotSource describes the origin of the snapshot.
type InstanceSnapshotSource struct {
	// InstanceRef points to the source Instance.
	InstanceRef corev1.ObjectReference `json:"instanceRef"`
	// EnvironmentName is the name of the environment inside the Instance to snapshot.
	EnvironmentName string `json:"environmentName"`
	// EnvironmentType is the type of the environment (e.g., VirtualMachine).
	// +optional
	EnvironmentType EnvironmentType `json:"environmentType,omitempty"`
	// TenantRef points to the Tenant owning the source Instance.
	// +optional
	TenantRef corev1.LocalObjectReference `json:"tenantRef,omitempty"`
	// TemplateRef points to the Template of the source Instance.
	// +optional
	TemplateRef corev1.ObjectReference `json:"templateRef,omitempty"`
	// WorkspaceRef points to the Workspace of the source Instance.
	// +optional
	WorkspaceRef corev1.LocalObjectReference `json:"workspaceRef,omitempty"`
	// PVCName is the name of the underlying PVC.
	// +optional
	PVCName string `json:"pvcName,omitempty"`
	// Disk contains the storage characteristics of the original PVC.
	// +optional
	Disk InstanceSnapshotDisk `json:"disk,omitempty"`
}

// InstanceSnapshotDestination describes where the snapshot will be stored.
type InstanceSnapshotDestination struct {
	// Scope is the requested destination scope (Private, Workspace, Public).
	Scope SnapshotDestinationScope `json:"scope"`
	// Namespace is the resolved destination namespace (frozen at creation time).
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// InstanceSnapshotSpec defines the desired state of InstanceSnapshot.
type InstanceSnapshotSpec struct {
	// DisplayName is a human-readable name for the snapshot.
	// +optional
	DisplayName string `json:"displayName,omitempty"`
	// Source describes the origin of the snapshot.
	Source InstanceSnapshotSource `json:"source"`
	// Destination describes where the snapshot will be stored.
	Destination InstanceSnapshotDestination `json:"destination"`
}

// SnapshotPhase describes the current phase of the InstanceSnapshot.
// +kubebuilder:validation:Enum=Pending;Ready;Failed
type SnapshotPhase string

const (
	// SnapshotPhasePending means the snapshot is being created.
	SnapshotPhasePending SnapshotPhase = "Pending"
	// SnapshotPhaseReady means the snapshot has been successfully created.
	SnapshotPhaseReady SnapshotPhase = "Ready"
	// SnapshotPhaseFailed means the snapshot creation failed.
	SnapshotPhaseFailed SnapshotPhase = "Failed"
)

// SnapshotArtifact describes the final artifact generated by the snapshot.
type SnapshotArtifact struct {
	// DataVolumeRef points to the generated DataVolume.
	// +optional
	DataVolumeRef corev1.ObjectReference `json:"dataVolumeRef,omitempty"`
}

// InstanceSnapshotStatus defines the observed state of InstanceSnapshot.
type InstanceSnapshotStatus struct {
	// Phase is the current phase of the snapshot.
	// +optional
	Phase SnapshotPhase `json:"phase,omitempty"`
	// Artifact contains references to the generated resources.
	// +optional
	Artifact SnapshotArtifact `json:"artifact,omitempty"`
	// Conditions hold the latest available observations of the snapshot state.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName="is"
// +kubebuilder:printcolumn:name="DisplayName",type=string,JSONPath=`.spec.displayName`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Scope",type=string,JSONPath=`.spec.destination.scope`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// InstanceSnapshot is the Schema for the instancesnapshots API.
type InstanceSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   InstanceSnapshotSpec   `json:"spec,omitempty"`
	Status InstanceSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceSnapshotList contains a list of InstanceSnapshot.
type InstanceSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceSnapshot `json:"items"`
}

func init() {
	SchemeBuilder.Register(&InstanceSnapshot{}, &InstanceSnapshotList{})
}
