---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: <vm_name>
  namespace: <namespace>
spec:
  terminationGracePeriodSeconds: 30
  domain:
    cpu:
      cores: 2
    resources:
      requests:
        cpu: 2
        memory: 4G
      limits:
        cpu: 2
        memory: 4G
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
  - name: containerdisk
    containerDisk:
      image: <user/image:latest>
  - name: cloudinitdisk
    cloudInitNoCloud:
      secretRef:
        name: <secret_name>
