# Default values for cloudimg registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configurations:
  dataRoot: "/data"
  readHeaderTimeoutSeconds: 2
  volume:
    size: "100Gi"
    accessMode: "ReadWriteMany"
    storageClass: "rook-cephfs-primary"

image:
  repository: crownlabs/cloudimg-registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
podAnnotations: {}
ingressAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 2000
  runAsGroup: 2000
  privileged: false

resources:
  limits:
    memory: 500Mi
    cpu: 1000m
  requests:
    memory: 500Mi
    cpu: 100m
