apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: jaeger
  namespace: observability
spec:
  rules:
  - host: jaeger.crown-labs.ipv6.polito.it
    http:
      paths:
      - backend:
          serviceName: jaeger-query
          servicePort: 16686
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - jaeger.crown-labs.ipv6.polito.it
    secretName: jaeger-cert
