apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-thanos-bucket
provisioner: ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: thanos
  objectStoreNamespace: rook-ceph
  region: us-east-1
