// Code generated by ifacemaker. DO NOT EDIT.

package common

import (
	"context"

	"github.com/Nerzal/gocloak/v13"
)

type KeycloakActorIface interface {
	IsInitialized() bool
	Reset()
	// GetAccessToken returns the access token of the actor.
	// It tries to refresh the token if it is nil or expired.
	GetAccessToken() string
	// GetUser returns the user associated with the given username.
	GetUser(ctx context.Context, username string) (*gocloak.User, error)
	// CreateUser creates a user in Keycloak.
	CreateUser(ctx context.Context, username string, email string, firstName string, lastName string) (string, error)
	DeleteUser(ctx context.Context, userID string) error
	GetRole(ctx context.Context, roleName string) (*gocloak.Role, error)
	CreateRole(ctx context.Context, roleName string, roleDescription string) (string, error)
	DeleteRole(ctx context.Context, roleName string) error
	GetUserRoles(ctx context.Context, userID string) ([]*gocloak.Role, error)
	AddUserToRoles(ctx context.Context, userID string, roles []*gocloak.Role) error
	RemoveUserFromRoles(ctx context.Context, userID string, roles []*gocloak.Role) error
}
