---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-labs
  namespace: {{ namespace_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: labtemplate-consumer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kubernetes:{{ course_group }}
