---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-labs-{{ username }}
  namespace: {{ namespace_name }}
subjects:
- kind: User
  name: {{ username }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: labinstance-consumer
  apiGroup: rbac.authorization.k8s.io