# Default values for frontend-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crownlabs/frontend-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

configuration:
  mountPath: /usr/share/nginx/html
  fileName: config.js
  backend:
    graphql: https://graphql.example.com
  oidc:
    clientId: <client-id>
    realm: <realm>
    providerUrl: https://auth.example.com/auth/

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations:
  reloader.stakater.com/auto: "true"
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  privileged: false

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hostname: crownlabs.example.com
  path: /
  secret: frontend-app-certificate

resources:
  limits:
    cpu: 1000m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 100Mi
