apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: keycloak-db-cluster
  namespace: keycloak-ha
spec:
  teamId: "keycloak"
  volume:
    storageClass: "rook-ceph-block"
    size: 10Gi
  numberOfInstances: 3
  users:
    keycloak: # database owner
    - superuser
    - createdb
  databases:
    keycloak: keycloak # dbname: owner
  postgresql:
    version: "12"
