//import { workspaces } from './tempData';
import { Template, WorkspaceRole } from '../../utils';

export const templates: Array<Template> = [
  {
    id: 't1',
    name: 'Template 1',
    gui: true,
    persistent: true,
    resources: {
      cpu: 4,
      disk: 50,
      memory: 8,
    },
    instances: [
      {
        id: 1,
        idTemplate: 't1',
        gui: true,
        persistent: true,
        tenantId: 's123456',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 1',
        ip: '192.168.1.1',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 2,
        idTemplate: 't1',
        gui: true,
        persistent: true,
        tenantId: 's123457',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 2',
        ip: '192.168.1.2',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 3,
        idTemplate: 't1',
        gui: true,
        persistent: true,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 3',
        ip: '192.168.1.3',
        status: 'VmiOff',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 4,
        idTemplate: 't1',
        gui: true,
        persistent: true,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 4',
        ip: '192.168.1.3',
        status: 'Failed',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
    ],
  },
  {
    id: 't2',
    name: 'Template 2',
    gui: false,
    persistent: false,
    resources: {
      cpu: 4,
      disk: 50,
      memory: 8,
    },
    instances: [
      {
        id: 1,
        idTemplate: 't2',
        gui: false,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 1',
        ip: '192.168.1.1',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 2,
        idTemplate: 't2',
        gui: false,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 2',
        ip: '192.168.1.2',
        status: 'Failed',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 3,
        idTemplate: 't2',
        gui: false,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 3',
        ip: '192.168.1.3',
        status: 'Starting',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
    ],
  },
  {
    id: 't3',
    name: 'Template 3',
    gui: true,
    persistent: false,
    resources: {
      cpu: 4,
      disk: 50,
      memory: 8,
    },
    instances: [
      {
        id: 1,
        idTemplate: 't3',
        gui: true,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 1',
        ip: '192.168.1.1',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 2,
        idTemplate: 't3',
        gui: true,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 2',
        ip: '192.168.1.2',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
      {
        id: 3,
        idTemplate: 't3',
        gui: true,
        persistent: false,
        tenantId: 'sXXXXXX',
        tenantDisplayName: 'Paolo Rossi',
        name: 'Instance 3',
        ip: '192.168.1.3',
        status: 'VmiReady',
        url: 'htp://urldiprova',
        timeStamp: 'Thu Jul 18 2013 15:48:59 GMT+0400',
      },
    ],
  },
];

export const workspaces = [
  {
    id: 'w1',
    title: 'Reti Locali e Data Center',
    role: 'manager' as WorkspaceRole,
    templates: [templates[0], templates[1]],
  },
  {
    id: 'w2',
    title: 'Cloud Computing',
    role: 'user' as WorkspaceRole,
    templates: templates,
  },
  {
    id: 'w3',
    title: 'Tecnologie e Servizi di Rete',
    role: 'user' as WorkspaceRole,
    templates: [templates[1], templates[2]],
  },
];

/* export const workspaces = [
  {
    workspaceId: 1,
    role: 'user' as WorkspaceRole,
  },
  {
    workspaceId: 2,
    role: 'manager' as WorkspaceRole,
  },
]; */
