name: Pull Request Labeler
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.CI_TOKEN }}"
          sync-labels: true
