name: Go
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_TOKEN }}
    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Build and Push Laboratory-Operator image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/laboratory-operator
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: operators/labInstance-operator/
        tags: "latest,${{ steps.tag.outputs.result }}"
    - name: Build and Push Frontend image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: webservice
        tags: "latest,${{ steps.tag.outputs.result }}"

