name: Dispatch Slash Commands
on:
  issue_comment:
    types:
      - created

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Slash Commands
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          reaction-token: ${{ secrets.CI_TOKEN }}
          issue-type: pull-request
          config: >
            [
              {
                "command": "merge",
                "permission": "write"
              },
              {
                "command": "rebase",
                "permission": "none"
              },
              {
                "command": "deploy-staging",
                "permission": "write"
              },
              {
                "command": "undeploy-staging",
                "permission": "write"
              },
              {
                "command": "hold",
                "permission": "none"
              },
              {
                "command": "unhold",
                "permission": "none"
              }
            ]
