apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labtemplate-consumer-operator
rules:
  - apiGroups:
      - template.crown.team.com
    resources:
      - labtemplates
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labinstance-consumer-operator
rules:
  - apiGroups:
      - instance.crown.team.com
    resources:
      - labinstances
    verbs:
      - get
      - create
      - update
      - list
      - patch
      - deletecollection
      - watch
      - delete

