---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-operator
  namespace: lab-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: lab-operator-cr
  namespace: lab-operator
subjects:
  - kind: ServiceAccount
    name: lab-operator
    namespace: lab-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin